DROP DATABASE IF EXISTS MEDIA;
CREATE DATABASE MEDIA;

USE MEDIA;

CREATE TABLE DOMAINS(
    DOMAIN VARCHAR(250) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DOMAINS PRIMARY KEY(DOMAIN)
);

CREATE TABLE USERS (
    TOKEN VARCHAR(25) NOT NULL,
    USER VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY(TOKEN)
);

CREATE TABLE USERSDOMAINS(
    DOMAIN VARCHAR(250) NOT NULL,
    TOKEN VARCHAR(25) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USERSDOMAINS01 FOREIGN KEY(DOMAIN) REFERENCES DOMAINS(DOMAIN) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_USERSDOMAINS02 FOREIGN KEY(TOKEN) REFERENCES USERS(TOKEN) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE RESOURCES(
    RESOURCE VARCHAR(200) NOT NULL,
    CONSTRAINT PK_RESOURCES PRIMARY KEY(RESOURCE),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RESOURCESDOMAINS(
    DOMAIN VARCHAR(250) NOT NULL,
    RESOURCE VARCHAR(200) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RESOURCESDOMAINS01 FOREIGN KEY(DOMAIN) REFERENCES DOMAINS(DOMAIN) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_RESOURCESDOMAINS02 FOREIGN KEY(RESOURCE) REFERENCES RESOURCES(RESOURCE) ON UPDATE CASCADE ON DELETE CASCADE
);