DROP DATABASE IF EXISTS MEDIA;
CREATE DATABASE MEDIA;

USE MEDIA;

CREATE TABLE APPLICATIONS(
    NAME VARCHAR(100) NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DOMAINS(
    DOMAIN VARCHAR(255) NOT NULL,
    APPLICATION_NAME VARCHAR(100) NOT NULL,
    RESTRICT_DOMAIN SMALLINT DEFAULT 1, -- If set to 0, the files will be visible from any request sources, if is set to 1, files will only be visible from the given domain
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(DOMAIN, APPLICATION_NAME),
    CONSTRAINT FK_DOMAINS01 FOREIGN KEY(APPLICATION_NAME) REFERENCES APPLICATIONS(NAME) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE USERS(
    USER INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USERROLES(
    USER INTEGER NOT NULL,
    DOMAIN VARCHAR(255) NOT NULL,
    APPLICATION_NAME VARCHAR(100) NOT NULL,
    PERMISSION_READ SMALLINT DEFAULT 1,
    PERMISSON_WRITE SMALLINT DEFAULT 0,
    PERMISSION_DELETE SMALLINT DEFAULT 0,
    PERMISSION_MANAGE SMALLINT DEFAULT 0,
    PRIMARY KEY(USER, DOMAIN, APPLICATION_NAME),
    CONSTRAINT FK_USERROLES01 FOREIGN KEY(USER) REFERENCES USERS(USER),
    CONSTRAINT FK_USERROLES02 FOREIGN KEY(DOMAIN, APPLICATION_NAME) REFERENCES DOMAINS(DOMAIN, APPLICATION_NAME) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE RESOURCES(
    DOMAIN VARCHAR(255) NOT NULL,
    APPLICATION_NAME VARCHAR(100) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    PRIMARY KEY(DOMAIN, APPLICATION_NAME, NAME),
    CONSTRAINT FK_RESOURCES01 FOREIGN KEY(DOMAIN, APPLICATION_NAME) REFERENCES DOMAINS(DOMAIN, APPLICATION_NAME) ON UPDATE CASCADE ON DELETE CASCADE
);